### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gumbobrot** [Sploups21/extension-spoofer#1]
.

**Comment by Sploups21** [comment]
Yooo, of course, you can use it ! And no need to credit me, its cool :)
(I just hope your stealer is designed for educational purposes haha)

**Comment by gumbobr0t** [comment]
oh wow thanks! and yep it is designed only for educational purposes to learn more about cybersec & python.

Since your Python skills seem to be pretty good and I've been looking for new developers for a long time, because I keep noticing that this project is very difficult, I would like to invite you to join our developer team or have a look at it.

Otherwise, you also seem to be very cool and helpful, so I would ask you to add me on Discord: gumbobrot :)


![Screenshot_20230825_151916_GitHub.jpg](https://github.com/Sploups21/extension-spoofer/assets/96620548/d0f943bf-2d1f-45af-becb-4d00cf7ec3f1)

![Screenshot_20230825_151922_GitHub.jpg](https://github.com/Sploups21/extension-spoofer/assets/96620548/7eedfa95-3631-4376-b157-b76387c6f7f2)

**Comment by Sploups21** [comment]
hell yeah, i'm interested :) I've added you on discord !
